### ISSUE TITLE
Two sitemapFriend call on the same page doesn't work

### ISSUE THREAD

**Issue by Spheerys** [yogoo/sitemapFriend#5]
Hi,

I'm trying to use 2 different call of the sitemapFriend snippet and it doens't works
I need two to make 2 site maps : one in french, the other in english

Here the code :

```
<h3>Sitemap in french</h3>
[[sitemapFriend? &startId=`50`]]

<h3>Sitemap in english</h3>
[[sitemapFriend? &startId=`96`]]
```

I tryied with or without cache/uncache call, I always have two times the same sitemap (two in french, or two in english)

What's wrong ?

**Comment by yogoo** [comment]
Hi Spheerys,

I'll need a lot more info than that to help out out.

1.- What do you mean by: « it doesn't work »? Provide me with softwares versions, steps to reproduce, what you expect, what happens instead.

2.- Is the static content of the page loading at all?

3.- What happens when you try with a single basic call such as
`[[sitemapFriend]]`
or
`[[sitemapFriend? &type=`xml`]]`

**Comment by Spheerys** [comment]
OK.
I'm using MODX 2.2.7 with sitemapFriend 1.0.2

I'm confronted to the problem on this webpage : http://dev.jldenois.com/error404

The code I used to do this is :

```
  <div class="span4">
    <p>Plan du site Français</p>
    [[sitemapFriend? &startId=`50`]]
  </div>

  <div class="span4">
    <p>Sitemap in English</p>
    [[sitemapFriend? &startId=`96`]]
  </div>
```

..where the startId are the parent of each language.

As you can see, the generated sitemaps are the same, despite the differents startId.
If I try to make uncached call, the generated sitemaps switch to english. But I can't have the right two sitemap : french AND english.

Strange isn't it ?

**Comment by yogoo** [comment]
Thanks for the details, I was able to reproduce the issue.

There's an odd behavior from Modx when calling $modx->getservice() multiple times on a single resource from within a snippet. It's unclear wether the bug originates from sitemapFriend or Modx. I'll need to investigate this further with the core team. It will take some time.

In the meantime and in your specific case, you could generate one 404 page for each language.
Since this organization would preserve the website's url scheme, it will be more consistent than having a single multi-language 404 page. It also scales better (think "more languages") and shrink better (think "independent languages", ie. less maintenance). Finally this might be an acceptable workaround until the issue is resolved.

Updates on the topic will be posted here.

**Comment by Spheerys** [comment]
Thanks for the analyse.
About the 2 error pages, one for each language : yes it should be the best idea, but I though MODx can only setup ONE error page (or maybe one per context, but I don't want to use context to manage bilinguism).

Anyway... I will wait for an issue, and for now I will keep only one french error page. It's best than no error page... :)

**Comment by yogoo** [comment]
Another way to handle it is to serve a localized 404 page via a snippet that would look for the language string in the referer to set the startId and fall back to the browser locale in case the referer isn't set. If both fail, fallback to French.

**Comment by yogoo** [comment]
Multiple calls can now be done on the same page (tested in modx 2.2.12-pl traditional). The issue was lying within modx.
